services:
  llamanexus:
    container_name: llamanexus
    image: makershop/llamanexus:cuda-12-latest
    pull_policy: always
    tty: true
    network_mode: host
    ports:
      - "50052:50052"
    command: worker --discovery
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
