services:
  llamanexus:
    container_name: llamanexus
    image: makershop/llamanexus:cuda-12-latest
    pull_policy: never
    #pull_policy: always
    tty: true
    network_mode: host
    ports:
      - "11434:11434"
      - "50051:50051"
    volumes:
      - ./models:/root/.cache/huggingface
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HUB_DISABLE_PROGRESS_BARS=0
      - TQDM_DISABLE=0
      - HF_TOKEN=${HF_TOKEN}
    command: serve --port 11434 --llama-port 8080 -v --discovery -- --jinja --context-shift
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
