services:
  llamanexus:
    container_name: llamanexus
    image: makershop/llamanexus:latest
    pull_policy: always
    tty: true
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./models:/root/.cache/huggingface
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HUB_DISABLE_PROGRESS_BARS=0
      - TQDM_DISABLE=0
      - HF_TOKEN=${HF_TOKEN} # remove if not used
    command: serve --port 11434 --llamaport 8080 -v # -- --rpc 192.168.1.10:50052,192.168.1.11:50052 # use double dash to separate arguments to pass to llama-server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
