services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:dev
    # For routing devices to flash. Make sure this matched your adapter location
    #devices:
    #  - source: /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_54:32:04:0A:8A:9C-if00
    #    target: /dev/ttyACM0  
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
